/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShuttleStatus = IDL.Variant({
  'delayed' : IDL.Null,
  'cancelled' : IDL.Null,
  'running' : IDL.Null,
});
export const ShuttleStatusRecord = IDL.Record({
  'status' : ShuttleStatus,
  'alternateRouteNote' : IDL.Text,
  'updatedAt' : IDL.Int,
  'statusNote' : IDL.Text,
  'busId' : Id,
});
export const Bus = IDL.Record({
  'id' : Id,
  'busName' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'cityId' : Id,
  'returnDepartureTime' : IDL.Text,
  'routeStops' : IDL.Vec(IDL.Text),
  'returnArrivalTime' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const City = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
export const Driver = IDL.Record({
  'id' : Id,
  'busId' : Id,
  'phone' : IDL.Text,
  'driverName' : IDL.Text,
});
export const HelpContact = IDL.Record({
  'id' : Id,
  'contactName' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'isImportant' : IDL.Bool,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'cityId' : Id,
  'rollNumber' : IDL.Text,
  'busId' : Id,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'registeredAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBus' : IDL.Func(
      [Id, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Id],
      [],
    ),
  'addCity' : IDL.Func([IDL.Text], [Id], []),
  'addDriver' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
  'addHelpContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Id],
      [],
    ),
  'addNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Id], []),
  'addSampleData' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'deleteBus' : IDL.Func([Id], [], []),
  'deleteCity' : IDL.Func([Id], [], []),
  'deleteDriver' : IDL.Func([Id], [], []),
  'deleteHelpContact' : IDL.Func([Id], [], []),
  'deleteNotification' : IDL.Func([Id], [], []),
  'getAllShuttleStatuses' : IDL.Func(
      [],
      [IDL.Vec(ShuttleStatusRecord)],
      ['query'],
    ),
  'getBus' : IDL.Func([Id], [Bus], ['query']),
  'getBusCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
  'getBusesForCity' : IDL.Func([Id], [IDL.Vec(Bus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCities' : IDL.Func([], [IDL.Vec(City)], ['query']),
  'getCity' : IDL.Func([Id], [City], ['query']),
  'getCityCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDriver' : IDL.Func([Id], [Driver], ['query']),
  'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getDriversForBus' : IDL.Func([Id], [IDL.Vec(Driver)], ['query']),
  'getHelpContact' : IDL.Func([Id], [HelpContact], ['query']),
  'getHelpContacts' : IDL.Func([], [IDL.Vec(HelpContact)], ['query']),
  'getNotification' : IDL.Func([Id], [Notification], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getReadNotifications' : IDL.Func([], [IDL.Vec(Id)], ['query']),
  'getShuttleStatus' : IDL.Func(
      [Id],
      [IDL.Opt(ShuttleStatusRecord)],
      ['query'],
    ),
  'getStudentCountPerBus' : IDL.Func([Id], [IDL.Nat], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentsForBus' : IDL.Func([Id], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([Id], [], []),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Id, Id],
      [Id],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setupSampleData' : IDL.Func([], [], []),
  'updateBus' : IDL.Func(
      [
        Id,
        Id,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateCity' : IDL.Func([Id, IDL.Text], [], []),
  'updateDriver' : IDL.Func([Id, Id, IDL.Text, IDL.Text], [], []),
  'updateHelpContact' : IDL.Func(
      [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNotification' : IDL.Func([Id, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateShuttleStatus' : IDL.Func(
      [Id, ShuttleStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShuttleStatus = IDL.Variant({
    'delayed' : IDL.Null,
    'cancelled' : IDL.Null,
    'running' : IDL.Null,
  });
  const ShuttleStatusRecord = IDL.Record({
    'status' : ShuttleStatus,
    'alternateRouteNote' : IDL.Text,
    'updatedAt' : IDL.Int,
    'statusNote' : IDL.Text,
    'busId' : Id,
  });
  const Bus = IDL.Record({
    'id' : Id,
    'busName' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'cityId' : Id,
    'returnDepartureTime' : IDL.Text,
    'routeStops' : IDL.Vec(IDL.Text),
    'returnArrivalTime' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const City = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
  const Driver = IDL.Record({
    'id' : Id,
    'busId' : Id,
    'phone' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const HelpContact = IDL.Record({
    'id' : Id,
    'contactName' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'isImportant' : IDL.Bool,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'cityId' : Id,
    'rollNumber' : IDL.Text,
    'busId' : Id,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBus' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Id],
        [],
      ),
    'addCity' : IDL.Func([IDL.Text], [Id], []),
    'addDriver' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
    'addHelpContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Id],
        [],
      ),
    'addNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Id], []),
    'addSampleData' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'deleteBus' : IDL.Func([Id], [], []),
    'deleteCity' : IDL.Func([Id], [], []),
    'deleteDriver' : IDL.Func([Id], [], []),
    'deleteHelpContact' : IDL.Func([Id], [], []),
    'deleteNotification' : IDL.Func([Id], [], []),
    'getAllShuttleStatuses' : IDL.Func(
        [],
        [IDL.Vec(ShuttleStatusRecord)],
        ['query'],
      ),
    'getBus' : IDL.Func([Id], [Bus], ['query']),
    'getBusCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
    'getBusesForCity' : IDL.Func([Id], [IDL.Vec(Bus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCities' : IDL.Func([], [IDL.Vec(City)], ['query']),
    'getCity' : IDL.Func([Id], [City], ['query']),
    'getCityCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDriver' : IDL.Func([Id], [Driver], ['query']),
    'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getDriversForBus' : IDL.Func([Id], [IDL.Vec(Driver)], ['query']),
    'getHelpContact' : IDL.Func([Id], [HelpContact], ['query']),
    'getHelpContacts' : IDL.Func([], [IDL.Vec(HelpContact)], ['query']),
    'getNotification' : IDL.Func([Id], [Notification], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getReadNotifications' : IDL.Func([], [IDL.Vec(Id)], ['query']),
    'getShuttleStatus' : IDL.Func(
        [Id],
        [IDL.Opt(ShuttleStatusRecord)],
        ['query'],
      ),
    'getStudentCountPerBus' : IDL.Func([Id], [IDL.Nat], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudentsForBus' : IDL.Func([Id], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([Id], [], []),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Id, Id],
        [Id],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setupSampleData' : IDL.Func([], [], []),
    'updateBus' : IDL.Func(
        [
          Id,
          Id,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateCity' : IDL.Func([Id, IDL.Text], [], []),
    'updateDriver' : IDL.Func([Id, Id, IDL.Text, IDL.Text], [], []),
    'updateHelpContact' : IDL.Func(
        [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNotification' : IDL.Func([Id, IDL.Text, IDL.Text, IDL.Bool], [], []),
    'updateShuttleStatus' : IDL.Func(
        [Id, ShuttleStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };