/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bus {
  'id' : Id,
  'busName' : string,
  'arrivalTime' : string,
  'departureTime' : string,
  'cityId' : Id,
  'returnDepartureTime' : string,
  'routeStops' : Array<string>,
  'returnArrivalTime' : string,
}
export interface City { 'id' : Id, 'name' : string }
export interface Driver {
  'id' : Id,
  'busId' : Id,
  'phone' : string,
  'driverName' : string,
}
export interface HelpContact {
  'id' : Id,
  'contactName' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type Id = bigint;
export interface Notification {
  'id' : Id,
  'title' : string,
  'isImportant' : boolean,
  'createdAt' : bigint,
  'message' : string,
}
export type ShuttleStatus = { 'delayed' : null } |
  { 'cancelled' : null } |
  { 'running' : null };
export interface ShuttleStatusRecord {
  'status' : ShuttleStatus,
  'alternateRouteNote' : string,
  'updatedAt' : bigint,
  'statusNote' : string,
  'busId' : Id,
}
export interface Student {
  'id' : Id,
  'name' : string,
  'cityId' : Id,
  'rollNumber' : string,
  'busId' : Id,
  'phone' : string,
  'department' : string,
  'registeredAt' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBus' : ActorMethod<
    [Id, string, Array<string>, string, string, string, string],
    Id
  >,
  'addCity' : ActorMethod<[string], Id>,
  'addDriver' : ActorMethod<[Id, string, string], Id>,
  'addHelpContact' : ActorMethod<[string, string, string, string], Id>,
  'addNotification' : ActorMethod<[string, string, boolean], Id>,
  'addSampleData' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'deleteBus' : ActorMethod<[Id], undefined>,
  'deleteCity' : ActorMethod<[Id], undefined>,
  'deleteDriver' : ActorMethod<[Id], undefined>,
  'deleteHelpContact' : ActorMethod<[Id], undefined>,
  'deleteNotification' : ActorMethod<[Id], undefined>,
  'getAllShuttleStatuses' : ActorMethod<[], Array<ShuttleStatusRecord>>,
  'getBus' : ActorMethod<[Id], Bus>,
  'getBusCount' : ActorMethod<[], bigint>,
  'getBuses' : ActorMethod<[], Array<Bus>>,
  'getBusesForCity' : ActorMethod<[Id], Array<Bus>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCities' : ActorMethod<[], Array<City>>,
  'getCity' : ActorMethod<[Id], City>,
  'getCityCount' : ActorMethod<[], bigint>,
  'getDriver' : ActorMethod<[Id], Driver>,
  'getDrivers' : ActorMethod<[], Array<Driver>>,
  'getDriversForBus' : ActorMethod<[Id], Array<Driver>>,
  'getHelpContact' : ActorMethod<[Id], HelpContact>,
  'getHelpContacts' : ActorMethod<[], Array<HelpContact>>,
  'getNotification' : ActorMethod<[Id], Notification>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getReadNotifications' : ActorMethod<[], Array<Id>>,
  'getShuttleStatus' : ActorMethod<[Id], [] | [ShuttleStatusRecord]>,
  'getStudentCountPerBus' : ActorMethod<[Id], bigint>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getStudentsForBus' : ActorMethod<[Id], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[Id], undefined>,
  'registerStudent' : ActorMethod<[string, string, string, string, Id, Id], Id>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setupSampleData' : ActorMethod<[], undefined>,
  'updateBus' : ActorMethod<
    [Id, Id, string, Array<string>, string, string, string, string],
    undefined
  >,
  'updateCity' : ActorMethod<[Id, string], undefined>,
  'updateDriver' : ActorMethod<[Id, Id, string, string], undefined>,
  'updateHelpContact' : ActorMethod<
    [Id, string, string, string, string],
    undefined
  >,
  'updateNotification' : ActorMethod<[Id, string, string, boolean], undefined>,
  'updateShuttleStatus' : ActorMethod<
    [Id, ShuttleStatus, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];