/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HelpContact {
    id: Id;
    contactName: string;
    role: string;
    email: string;
    phone: string;
}
export interface ShuttleStatusRecord {
    status: ShuttleStatus;
    alternateRouteNote: string;
    updatedAt: bigint;
    statusNote: string;
    busId: Id;
}
export interface Driver {
    id: Id;
    busId: Id;
    phone: string;
    driverName: string;
}
export interface Notification {
    id: Id;
    title: string;
    isImportant: boolean;
    createdAt: bigint;
    message: string;
}
export type Id = bigint;
export interface Bus {
    id: Id;
    busName: string;
    arrivalTime: string;
    departureTime: string;
    cityId: Id;
    returnDepartureTime: string;
    routeStops: Array<string>;
    returnArrivalTime: string;
}
export interface City {
    id: Id;
    name: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Student {
    id: Id;
    name: string;
    cityId: Id;
    rollNumber: string;
    busId: Id;
    phone: string;
    department: string;
    registeredAt: bigint;
}
export enum ShuttleStatus {
    delayed = "delayed",
    cancelled = "cancelled",
    running = "running"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBus(cityId: Id, busName: string, routeStops: Array<string>, departureTime: string, arrivalTime: string, returnDepartureTime: string, returnArrivalTime: string): Promise<Id>;
    addCity(name: string): Promise<Id>;
    addDriver(busId: Id, driverName: string, phone: string): Promise<Id>;
    addHelpContact(contactName: string, role: string, phone: string, email: string): Promise<Id>;
    addNotification(title: string, message: string, isImportant: boolean): Promise<Id>;
    addSampleData(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearAllData(): Promise<void>;
    deleteBus(id: Id): Promise<void>;
    deleteCity(id: Id): Promise<void>;
    deleteDriver(id: Id): Promise<void>;
    deleteHelpContact(id: Id): Promise<void>;
    deleteNotification(id: Id): Promise<void>;
    getAllShuttleStatuses(): Promise<Array<ShuttleStatusRecord>>;
    getBus(id: Id): Promise<Bus>;
    getBusCount(): Promise<bigint>;
    getBuses(): Promise<Array<Bus>>;
    getBusesForCity(cityId: Id): Promise<Array<Bus>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCities(): Promise<Array<City>>;
    getCity(id: Id): Promise<City>;
    getCityCount(): Promise<bigint>;
    getDriver(id: Id): Promise<Driver>;
    getDrivers(): Promise<Array<Driver>>;
    getDriversForBus(busId: Id): Promise<Array<Driver>>;
    getHelpContact(id: Id): Promise<HelpContact>;
    getHelpContacts(): Promise<Array<HelpContact>>;
    getNotification(id: Id): Promise<Notification>;
    getNotifications(): Promise<Array<Notification>>;
    getReadNotifications(): Promise<Array<Id>>;
    getShuttleStatus(busId: Id): Promise<ShuttleStatusRecord | null>;
    getStudentCountPerBus(busId: Id): Promise<bigint>;
    getStudents(): Promise<Array<Student>>;
    getStudentsForBus(busId: Id): Promise<Array<Student>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: Id): Promise<void>;
    registerStudent(name: string, rollNumber: string, department: string, phone: string, cityId: Id, busId: Id): Promise<Id>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setupSampleData(): Promise<void>;
    updateBus(id: Id, cityId: Id, busName: string, routeStops: Array<string>, departureTime: string, arrivalTime: string, returnDepartureTime: string, returnArrivalTime: string): Promise<void>;
    updateCity(id: Id, name: string): Promise<void>;
    updateDriver(id: Id, busId: Id, driverName: string, phone: string): Promise<void>;
    updateHelpContact(id: Id, contactName: string, role: string, phone: string, email: string): Promise<void>;
    updateNotification(id: Id, title: string, message: string, isImportant: boolean): Promise<void>;
    updateShuttleStatus(busId: Id, status: ShuttleStatus, statusNote: string, alternateRouteNote: string): Promise<void>;
}
import type { Id as _Id, ShuttleStatus as _ShuttleStatus, ShuttleStatusRecord as _ShuttleStatusRecord, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBus(arg0: Id, arg1: string, arg2: Array<string>, arg3: string, arg4: string, arg5: string, arg6: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addBus(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBus(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addCity(arg0: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCity(arg0);
            return result;
        }
    }
    async addDriver(arg0: Id, arg1: string, arg2: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addDriver(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDriver(arg0, arg1, arg2);
            return result;
        }
    }
    async addHelpContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addHelpContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHelpContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: string, arg2: boolean): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async addSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleData();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async deleteBus(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBus(arg0);
            return result;
        }
    }
    async deleteCity(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCity(arg0);
            return result;
        }
    }
    async deleteDriver(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriver(arg0);
            return result;
        }
    }
    async deleteHelpContact(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHelpContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHelpContact(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async getAllShuttleStatuses(): Promise<Array<ShuttleStatusRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShuttleStatuses();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShuttleStatuses();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBus(arg0: Id): Promise<Bus> {
        if (this.processError) {
            try {
                const result = await this.actor.getBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBus(arg0);
            return result;
        }
    }
    async getBusCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusCount();
            return result;
        }
    }
    async getBuses(): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuses();
            return result;
        }
    }
    async getBusesForCity(arg0: Id): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusesForCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusesForCity(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCities(): Promise<Array<City>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCities();
            return result;
        }
    }
    async getCity(arg0: Id): Promise<City> {
        if (this.processError) {
            try {
                const result = await this.actor.getCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCity(arg0);
            return result;
        }
    }
    async getCityCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityCount();
            return result;
        }
    }
    async getDriver(arg0: Id): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return result;
        }
    }
    async getDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrivers();
            return result;
        }
    }
    async getDriversForBus(arg0: Id): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriversForBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriversForBus(arg0);
            return result;
        }
    }
    async getHelpContact(arg0: Id): Promise<HelpContact> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpContact(arg0);
            return result;
        }
    }
    async getHelpContacts(): Promise<Array<HelpContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpContacts();
            return result;
        }
    }
    async getNotification(arg0: Id): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotification(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getReadNotifications(): Promise<Array<Id>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadNotifications();
            return result;
        }
    }
    async getShuttleStatus(arg0: Id): Promise<ShuttleStatusRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShuttleStatus(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShuttleStatus(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentCountPerBus(arg0: Id): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCountPerBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCountPerBus(arg0);
            return result;
        }
    }
    async getStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return result;
        }
    }
    async getStudentsForBus(arg0: Id): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsForBus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsForBus(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Id, arg5: Id): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setupSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setupSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupSampleData();
            return result;
        }
    }
    async updateBus(arg0: Id, arg1: Id, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBus(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBus(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateCity(arg0: Id, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCity(arg0, arg1);
            return result;
        }
    }
    async updateDriver(arg0: Id, arg1: Id, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHelpContact(arg0: Id, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelpContact(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelpContact(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateNotification(arg0: Id, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotification(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotification(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateShuttleStatus(arg0: Id, arg1: ShuttleStatus, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShuttleStatus(arg0, to_candid_ShuttleStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShuttleStatus(arg0, to_candid_ShuttleStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
function from_candid_ShuttleStatusRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShuttleStatusRecord): ShuttleStatusRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ShuttleStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShuttleStatus): ShuttleStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShuttleStatusRecord]): ShuttleStatusRecord | null {
    return value.length === 0 ? null : from_candid_ShuttleStatusRecord_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ShuttleStatus;
    alternateRouteNote: string;
    updatedAt: bigint;
    statusNote: string;
    busId: _Id;
}): {
    status: ShuttleStatus;
    alternateRouteNote: string;
    updatedAt: bigint;
    statusNote: string;
    busId: Id;
} {
    return {
        status: from_candid_ShuttleStatus_n6(_uploadFile, _downloadFile, value.status),
        alternateRouteNote: value.alternateRouteNote,
        updatedAt: value.updatedAt,
        statusNote: value.statusNote,
        busId: value.busId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    cancelled: null;
} | {
    running: null;
}): ShuttleStatus {
    return "delayed" in value ? ShuttleStatus.delayed : "cancelled" in value ? ShuttleStatus.cancelled : "running" in value ? ShuttleStatus.running : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShuttleStatusRecord>): Array<ShuttleStatusRecord> {
    return value.map((x)=>from_candid_ShuttleStatusRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ShuttleStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShuttleStatus): _ShuttleStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShuttleStatus): {
    delayed: null;
} | {
    cancelled: null;
} | {
    running: null;
} {
    return value == ShuttleStatus.delayed ? {
        delayed: null
    } : value == ShuttleStatus.cancelled ? {
        cancelled: null
    } : value == ShuttleStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
